import  React from "react";
import { View, Text, StyleSheet, TextInput } from "react-native";
import Button from './Button';

import PageHeader2 from './PageHeader2';
import { Constants } from './conststants';
//import ProgressBar from "./ProgressBar";


//import Progress from "react-native-progress";
//const BackgroundGreyImage = require("../assets/Images/Background_grey_cube.png");

/*
const DialCodes = {
  "Afghanistan": "+93",
  "Albania": "+355",
  "Algeria": "+213",
  "American Samoa": "+684",
    'Andorra':	      '+376',
    'Angola':	        '+244',
    'Anguilla':	      '+1-264',
    'Antarctica':	    '+672',
    'Antigua':	      '+1-268',
    'Argentina':	    '+54',
    'Armenia':	      '+374',
    'Aruba':	        '+297',
    'Ascension':	    '+247',
    'Australia':	    '+61',
    'Australian Territories':	'+672',
    'Austria':	'       +43',
    'Azerbaijan':	      '+994',
    'Bahamas':	      '+1-242',
    'Bahrain':	      '+973',
    'Bangladesh':	    '+880',
    'Barbados':	      '+1-246',
    'Belarus':	      '+375',
    'Belgium':	      '+32',
    'Belize':	        '+501',
    'Benin':	        '+229',
    'Bermuda':	      '+1-441',
    'Bhutan':	        '+975',
    'Bolivia':	      '+591',
    'Bosnia & Herzegovina':	'+387',
    'Botswana':	      '+267',
    'Brazil':	        '+55	0014',
    'British Virgin Islands':	'+1-284',
    'Brunei Darussalam': '+673*',
    'Bulgaria':	      '+359',
    'Burkina Faso':	'+226',
    'Burundi':	'+257',
    'Cambodia':	'+855',
    'Cameroon':	'+237',
    'Canada':	'+1	011	1',
    'Cape Verde Islands':	'+238',
    'Cayman Islands':	'+1-345',
    'Central African Republic':	'+236',
    'Chad':	'+235	15',
    'Chatham Islands (New Zealand)':	'+64',
    'Chile':	'+56',
    'China (PRC)':	'+86',
      'Christmas Island':	'+61',
    'Comoros':	'+269',
    'Congo':	'+242',
    'Congo(Democratic Republic of)':	'+243',
    'Cook Islands':'	+682',
    'Costa Rica':	'+506',
    'Cote d\'Ivoire (Ivory Coast)':	'+225',
    'Croatia':	'+385',
    'Cuba':	'+53',
    'Cyprus':	'+357',
    'Czech Republic':	'+420',
    'Denmark':	'+45',
    'Diego Garcia':	'+246',
    'Djibouti':	'+253',
    'Dominica':	'+1-767*',
    'Dominican Republic':	'+1-809*',
  'East Timor':       '+670',
  'Easter Island':	'+56',
  'Ecuador':	'+593',
  'Egypt':	'+20',
  'El Salvador':	'+503',
  'Equatorial Guinea':	'+240',
  'Eritrea':	'+291',
  'Estonia':	'+372',
  'Ethiopia':	'+251',
  'Falkland Islands':	'+500',
  'Faroe Islands':	'+298',
  'Fiji Islands':'+679',
  'Finland':	'+358',
  'France':	'+33',
  'French Antilles':	'+596',
  'French Guiana':	'+594',
  'French Polynesia':	'+689',
  'Gabonese Republic':	'+241',
  'Gambia':	'+220',
  'Georgia':	'+995',
  'Germany':	'+49',
  'Ghana':	'+233',
  'Gibraltar':	'+350',
  'Greece':	'+30',
  'Greenland':	'+299',
  'Grenada':	'+1-473',
  'Guadeloupe':'	+590',
  'Guam':	'+1-671*',
  'Guatemala':	'+502',
  'Guinea Bissau':	'+245',
  'Guinea':	'+224',
  'Guyana':	'+592',
  'Haiti':	'+509',
  'Honduras':	'+504',
  'Hong Kong':	'+852',
  'Hungary':	'+36',
  'Iceland':	'+354',
  'India':	'+91',
  'Indonesia':	'+62',
  'Iran':	'+98',
  'Iraq':	'+964',
  'Ireland':	'+353',
  'Israel':	'+972',
  'Italy':	'+39',
  'Jamaica':	'+1-876*',
  'Japan':	'+81'	,
  'Jordan':	'+962',
  'Kazakhstan':	'+7',
  'Kenya':	'+254',
  'Kiribati':	'+686',
  'Korea (North)':	'+850',
  'Korea (South)':	'+82',
  'Kuwait':	'+965',
  'Kyrgyz Republic':	'+996',
  'Laos':	'+856',
  'Latvia':'	+371',
  'Lebanon':	'+961',
  'Lesotho':	'+266',
  'Liberia':	'+231',
  'Libya':	'+218',
  'Liechtenstein':	'+423',
  'Lithuania':	'+370',
  'Luxembourg':	'+352',
  'Macao':	'+853',
  'Macedonia':	'+389',
  'Madagascar':	'+261',
  'Malawi':	'+265',
  'Malaysia':	'+60',
  'Maldives':	'+960',
  'Mali Republic':	'+223',
  'Malta':	'+356',
  'Marshall Islands':	'+692',
  'Martinique':	'+596',
  'Mauritania':	'+222',
  'Mauritius':	'+230',
  'Mayotte Island':	'+269',
  'Mexico':	'+52',
  'Micronesia':	'+691',
  'Midway Island':	'+1-808*',
  'Moldova':	'+373',
  'Monaco':	'+377',
  'Mongolia':'	+976',
  'Montserrat':	'+1-664*',
  'Morocco':	'+212',
  'Mozambique':	'+258',
  'Myanmar':	'+95',
  'Namibia':	'+264',
  'Nauru':	'+674',
  'Nepal':	'+977',
  'Netherlands':	'+31',
  'Netherlands Antilles':	'+599',
  'Nevis':	'+1-869*',
  'New Caledonia':	'+687',
  'New Zealand':	'+64',
  'Nicaragua':	'+505',
  'Niger':	'+227',
  'Nigeria':	'+234',
  'Niue':	'+683',
  'Norfolk Island':	'+672',
  'Northern Marine Islands':	'+1-670*',
  'Norway':	'+47',
  'Oman':	'+968',
  'Pakistan':	'+92',
  'Palau':	'+680',
  'Panama':	'+507',
  'Papua New Guinea':	'+675',
  'Paraguay':	'+595',
  'Peru':	'+51',
  'Philippines':	'+63',
  'Poland':	'+48	0*',
  'Portugal':	'+351',
  'Puerto Rico':	'+1-787',
  'Qatar':	'+974',
  'Reunion Island':	'+262',
  'Romania':	'+40',
  'Russia':	'+7',
  'Rwanda':	'+250',
  'St. Helena':	'+290',
  'St. Kitts/Nevis':	'+1-869*',
  'St Lucia':	'+1-758*',
  'St. Pierre & Miquelon':	'+508',
  'St. Vincent & Grenadines':	'+1-784*',
  'San Marino':	'+378',
  'Sao Tomo and Principe':	'+239',
  'Saudi Arabia':	'+966',
  'Senegal':	'+221',
  'Serbia & Montenegro':	'+381',
  'Seychelles Republic':	'+248',
  'Sierra Leone':	'+232',
  'Singapore':	'+65',
  'Slovak Republic':	'+421',
  'Slovenia':	'+386',
  'Solomon Islands':	'+677',
  'Somalia':	'+252',
  'South Africa':	'+27',
  'Spain':	'+34',
  'Sri Lanka':	'+94',
  'Sudan':	'+249',
  'Suriname':	'+597',
  'Swaziland':	'+268',
  'Sweden':	'+46',
  'Switzerland':	'+41',
  'Syria':	'+963',
  'Taiwan':	'+886',
  'Tajikistan':	'+992',
  'Tanzania':	'+255',
  'Thailand':	'+66',
  'Togolese Republic':	'+228',
  'Tokelau':	'+690',
  'Tonga Islands':	'+676',
  'Trinidad & Tobago':	'+1-868',
  'Tunisia':	'+216',
  'Turkey':	'+90',
  'Turkmenistan':	'+993',
  'Turks & Caicos Islands':	+'1 649',
  'Tuvalu':	'+688',
  'Uganda':	'+256',
  'Ukraine':	'+380',
  'United Arab Emirates':	'+971',
  'United Kingdom':	'+44',
  'USA Area Codes':	'+1',
  'US Virgin Islands':	'+1-340',
  'Uruguay':	'+598',
  'Uzbekistan':'+998',
  'Vanuatu':	'+678',
  'Vietnam':	'+84',
  'Venezuela':	'+58',
  'Yemen':	'+998',
  'Zambia':	'+260',
  'Zimbabwe':	'+263',
};
*/

const DialCodesArr = [
  { 'Country' :  'Afghanistan', 'Code': '+93' },
  {'Country':  'Albania', 'Code': '+355'},
  {'Country':  'Algeria', 'Code': '+213'},
  {'Country':  'American Samoa', 'Code': '+684'},
  {'Country':  'Andorra', 'Code':	      '+376'},
  {'Country':  'Angola', 'Code':	        '+244'},
  {'Country':  'Anguilla', 'Code':	      '+1-264'},
  {'Country':  'Antarctica', 'Code':	    '+672'},
  {'Country':  'Antigua', 'Code':	      '+1-268'},
  {'Country':  'Argentina', 'Code':	    '+54'},
  {'Country':  'Armenia', 'Code':	      '+374'},
  {'Country':  'Aruba', 'Code':	        '+297'},
  {'Country':  'Ascension', 'Code':	    '+247'},
  {'Country':  'Australia', 'Code':	    '+61'},
  {'Country':  'Australian Territories', 'Code':	'+672'},
  {'Country':  'Austria', 'Code':	'       +43'},
  {'Country':  'Azerbaijan', 'Code':	      '+994'},
  {'Country':  'Bahamas', 'Code':	      '+1-242'},
  {'Country':  'Bahrain', 'Code':	      '+973'},
  {'Country':  'Bangladesh', 'Code':	    '+880'},
  {'Country':  'Barbados', 'Code':	      '+1-246'},
  {'Country':  'Belarus', 'Code':	      '+375'},
  {'Country':  'Belgium', 'Code':	      '+32'},
  {'Country':  'Belize', 'Code':	        '+501'},
  {'Country':  'Benin', 'Code':	        '+229'},
  {'Country':  'Bermuda', 'Code':	      '+1-441'},
  {'Country':  'Bhutan', 'Code':	        '+975'},
  {'Country':  'Bolivia', 'Code':	      '+591'},
  {'Country':  'Bosnia & Herzegovina', 'Code':	'+387'},
  {'Country':  'Botswana', 'Code':	      '+267'},
  {'Country':  'Brazil', 'Code':	        '+55	0014'},
  {'Country':  'British Virgin Islands', 'Code':	'+1-284'},
  {'Country':  'Brunei Darussalam', 'Code': '+673*'},
  {'Country':  'Bulgaria', 'Code':	      '+359'},
  {'Country':  'Burkina Faso', 'Code':	'+226'},
  {'Country':  'Burundi', 'Code':	'+257'},
  {'Country':  'Cambodia', 'Code':	'+855'},
  {'Country':  'Cameroon', 'Code':	'+237'},
  {'Country':  'Canada', 'Code':	'+1	011	1'},
  {'Country':  'Cape Verde Islands', 'Code':	'+238'},
  {'Country':  'Cayman Islands', 'Code':	'+1-345'},
  {'Country':  'Central African Republic', 'Code':	'+236'},
  {'Country':  'Chad', 'Code':	'+235	15'},
  {'Country':  'Chatham Islands (New Zealand)', 'Code':	'+64'},
  {'Country':  'Chile', 'Code':	'+56'},
  {'Country':  'China (PRC)', 'Code':	'+86'},
  {'Country':  'Christmas Island', 'Code':	'+61'},
  {'Country':  'Comoros', 'Code':	'+269'},
  {'Country':  'Congo', 'Code':	'+242'},
  {'Country':  'Congo(Democratic Republic of)', 'Code':	'+243'},
  {'Country':  'Cook Islands', 'Code':'	+682'},
  {'Country':  'Costa Rica', 'Code':	'+506'},
  {'Country':  'Cote d\'Ivoire (Ivory Coast)', 'Code':	'+225'},
  {'Country':  'Croatia', 'Code':	'+385'},
  {'Country':  'Cuba', 'Code':	'+53'},
  {'Country':  'Cyprus', 'Code':	'+357'},
  {'Country':  'Czech Republic', 'Code':	'+420'},
  {'Country':  'Denmark', 'Code':	'+45'},
  {'Country':  'Diego Garcia', 'Code':	'+246'},
  {'Country':  'Djibouti', 'Code':	'+253'},
  {'Country':  'Dominica', 'Code':	'+1-767*'},
  {'Country':  'Dominican Republic', 'Code':	'+1-809*'},
  {'Country':  'East Timor', 'Code':       '+670'},
  {'Country':  'Easter Island', 'Code':	'+56'},
  {'Country':  'Ecuador', 'Code':	'+593'},
  {'Country':  'Egypt', 'Code':	'+20'},
  {'Country':  'El Salvador', 'Code':	'+503'},
  {'Country':  'Equatorial Guinea', 'Code':	'+240'},
  {'Country':  'Eritrea', 'Code':	'+291'},
  {'Country':  'Estonia', 'Code':	'+372'},
  {'Country':  'Ethiopia', 'Code':	'+251'},
  {'Country':  'Falkland Islands', 'Code':	'+500'},
  {'Country':  'Faroe Islands', 'Code':	'+298'},
  {'Country':  'Fiji Islands', 'Code':'+679'},
  {'Country':  'Finland', 'Code':	'+358'},
  {'Country':  'France', 'Code':	'+33'},
  {'Country':  'French Antilles', 'Code':	'+596'},
  {'Country':  'French Guiana', 'Code':	'+594'},
  {'Country':  'French Polynesia', 'Code':	'+689'},
  {'Country':  'Gabonese Republic', 'Code':	'+241'},
  {'Country':  'Gambia', 'Code':	'+220'},
  {'Country':  'Georgia', 'Code':	'+995'},
  {'Country':  'Germany', 'Code':	'+49'},
  {'Country':  'Ghana', 'Code':	'+233'},
  {'Country':  'Gibraltar', 'Code':	'+350'},
  {'Country':  'Greece', 'Code':	'+30'},
  {'Country':  'Greenland', 'Code':	'+299'},
  {'Country':  'Grenada', 'Code':	'+1-473'},
  {'Country':  'Guadeloupe', 'Code':'	+590'},
  {'Country':  'Guam', 'Code':	'+1-671*'},
  {'Country':  'Guatemala', 'Code':	'+502'},
  {'Country':  'Guinea Bissau', 'Code':	'+245'},
  {'Country':  'Guinea', 'Code':	'+224'},
  {'Country':  'Guyana', 'Code':	'+592'},
  {'Country':  'Haiti', 'Code':	'+509'},
  {'Country':  'Honduras', 'Code':	'+504'},
  {'Country':  'Hong Kong', 'Code':	'+852'},
  {'Country':  'Hungary', 'Code':	'+36'},
  {'Country':  'Iceland', 'Code':	'+354'},
  {'Country':  'India', 'Code':	'+91'},
  {'Country':  'Indonesia', 'Code':	'+62'},
  {'Country':  'Iran', 'Code':	'+98'},
  {'Country':  'Iraq', 'Code':	'+964'},
  {'Country':  'Ireland', 'Code':	'+353'},
  {'Country':  'Israel', 'Code':	'+972'},
  {'Country':  'Italy', 'Code':	'+39'},
  {'Country':  'Jamaica', 'Code':	'+1-876*'},
  {'Country':  'Japan', 'Code':	'+81'},
  {'Country':  'Jordan', 'Code':	'+962'},
  {'Country':  'Kazakhstan', 'Code':	'+7'},
  {'Country':  'Kenya', 'Code':	'+254'},
  {'Country':  'Kiribati', 'Code':	'+686'},
  {'Country':  'Korea (North)', 'Code':	'+850'},
  {'Country':  'Korea (South)', 'Code':	'+82'},
  {'Country':  'Kuwait', 'Code':	'+965'},
  {'Country':  'Kyrgyz Republic', 'Code':	'+996'},
  {'Country':  'Laos', 'Code':	'+856'},
  {'Country':  'Latvia', 'Code':'	+371'},
  {'Country':  'Lebanon', 'Code':	'+961'},
  {'Country':  'Lesotho', 'Code':	'+266'},
  {'Country':  'Liberia', 'Code':	'+231'},
  {'Country':  'Libya', 'Code':	'+218'},
  {'Country':  'Liechtenstein', 'Code':	'+423'},
  {'Country':  'Lithuania', 'Code':	'+370'},
  {'Country':  'Luxembourg', 'Code':	'+352'},
  {'Country':  'Macao', 'Code':	'+853'},
  {'Country':  'Macedonia', 'Code':	'+389'},
  {'Country':  'Madagascar', 'Code':	'+261'},
  {'Country':  'Malawi', 'Code':	'+265'},
  {'Country':  'Malaysia', 'Code':	'+60'},
  {'Country':  'Maldives', 'Code':	'+960'},
  {'Country':  'Mali Republic', 'Code':	'+223'},
  {'Country':  'Malta', 'Code':	'+356'},
  {'Country':  'Marshall Islands', 'Code':	'+692'},
  {'Country':  'Martinique', 'Code':	'+596'},
  {'Country':  'Mauritania', 'Code':	'+222'},
  {'Country':  'Mauritius', 'Code':	'+230'},
  {'Country':  'Mayotte Island', 'Code':	'+269'},
  {'Country':  'Mexico', 'Code':	'+52'},
  {'Country':  'Micronesia', 'Code':	'+691'},
  {'Country':  'Midway Island', 'Code':	'+1-808*'},
  {'Country':  'Moldova', 'Code':	'+373'},
  {'Country':  'Monaco', 'Code':	'+377'},
  {'Country':  'Mongolia', 'Code':'	+976'},
  {'Country':  'Montserrat', 'Code':	'+1-664*'},
  {'Country':  'Morocco', 'Code':	'+212'},
  {'Country':  'Mozambique', 'Code':	'+258'},
  {'Country':  'Myanmar', 'Code':	'+95'},
  {'Country':  'Namibia', 'Code':	'+264'},
  {'Country':  'Nauru', 'Code':	'+674'},
  {'Country':  'Nepal', 'Code':	'+977'},
  {'Country':  'Netherlands', 'Code':	'+31'},
  {'Country':  'Netherlands Antilles', 'Code':	'+599'},
  {'Country':  'Nevis', 'Code':	'+1-869*'},
  {'Country':  'New Caledonia', 'Code':	'+687'},
  {'Country':  'New Zealand', 'Code':	'+64'},
  {'Country':  'Nicaragua', 'Code':	'+505'},
  {'Country':  'Niger', 'Code':	'+227'},
  {'Country':  'Nigeria', 'Code':	'+234'},
  {'Country':  'Niue', 'Code':	'+683'},
  {'Country':  'Norfolk Island', 'Code':	'+672'},
  {'Country':  'Northern Marine Islands', 'Code':	'+1-670*'},
  {'Country':  'Norway', 'Code':	'+47'},
  {'Country':  'Oman', 'Code':	'+968'},
  {'Country':  'Pakistan', 'Code':	'+92'},
  {'Country':  'Palau', 'Code':	'+680'},
  {'Country':  'Panama', 'Code':	'+507'},
  {'Country':  'Papua New Guinea', 'Code':	'+675'},
  {'Country':  'Paraguay', 'Code':	'+595'},
  {'Country':  'Peru', 'Code':	'+51'},
  {'Country':  'Philippines', 'Code':	'+63'},
  {'Country':  'Poland', 'Code':	'+48	0*'},
  {'Country':  'Portugal', 'Code':	'+351'},
  {'Country':  'Puerto Rico', 'Code':	'+1-787'},
  {'Country':  'Qatar', 'Code':	'+974'},
  {'Country':  'Reunion Island', 'Code':	'+262'},
  {'Country':  'Romania', 'Code':	'+40'},
  {'Country':  'Russia', 'Code':	'+7'},
  {'Country':  'Rwanda', 'Code':	'+250'},
  {'Country':  'St. Helena', 'Code':	'+290'},
  {'Country':  'St. Kitts/Nevis', 'Code':	'+1-869*'},
  {'Country':  'St Lucia', 'Code':	'+1-758*'},
  {'Country':  'St. Pierre & Miquelon', 'Code':	'+508'},
  {'Country':  'St. Vincent & Grenadines', 'Code':	'+1-784*'},
  {'Country':  'San Marino', 'Code':	'+378'},
  {'Country':  'Sao Tomo and Principe', 'Code':	'+239'},
  {'Country':  'Saudi Arabia', 'Code':	'+966'},
  {'Country':  'Senegal', 'Code':	'+221'},
  {'Country':  'Serbia & Montenegro', 'Code':	'+381'},
  {'Country':  'Seychelles Republic', 'Code':	'+248'},
  {'Country':  'Sierra Leone', 'Code':	'+232'},
  {'Country':  'Singapore', 'Code':	'+65'},
  {'Country':  'Slovak Republic', 'Code':	'+421'},
  {'Country':  'Slovenia', 'Code':	'+386'},
  {'Country':  'Solomon Islands', 'Code':	'+677'},
  {'Country':  'Somalia', 'Code':	'+252'},
  {'Country':  'South Africa', 'Code':	'+27'},
  {'Country':  'Spain', 'Code':	'+34'},
  {'Country':  'Sri Lanka', 'Code':	'+94'},
  {'Country':  'Sudan', 'Code':	'+249'},
  {'Country':  'Suriname', 'Code':	'+597'},
  {'Country':  'Swaziland', 'Code':	'+268'},
  {'Country':  'Sweden', 'Code':	'+46'},
  {'Country':  'Switzerland', 'Code':	'+41'},
  {'Country':  'Syria', 'Code':	'+963'},
  {'Country':  'Taiwan', 'Code':	'+886'},
  {'Country':  'Tajikistan', 'Code':	'+992'},
  {'Country':  'Tanzania', 'Code':	'+255'},
  {'Country':  'Thailand', 'Code':	'+66'},
  {'Country':  'Togolese Republic', 'Code':	'+228'},
  {'Country':  'Tokelau', 'Code':	'+690'},
  {'Country':  'Tonga Islands', 'Code':	'+676'},
  {'Country':  'Trinidad & Tobago', 'Code':	'+1-868'},
  {'Country':  'Tunisia', 'Code':	'+216'},
  {'Country':  'Turkey', 'Code':	'+90'},
  {'Country':  'Turkmenistan', 'Code':	'+993'},
  {'Country':  'Turks & Caicos Islands', 'Code':	+'1 649'},
  {'Country':  'Tuvalu', 'Code':	'+688'},
  {'Country':  'Uganda', 'Code':	'+256'},
  {'Country':  'Ukraine', 'Code':	'+380'},
  {'Country':  'United Arab Emirates', 'Code':	'+971'},
  {'Country':  'United Kingdom', 'Code':	'+44'},
  {'Country':  'USA Area Codes', 'Code':	'+1'},
  {'Country':  'US Virgin Islands', 'Code':	'+1-340'},
  {'Country':  'Uruguay', 'Code':	'+598'},
  {'Country':  'Uzbekistan', 'Code':'+998'},
  {'Country':  'Vanuatu', 'Code':	'+678'},
  {'Country':  'Vietnam', 'Code':	'+84'},
  {'Country':  'Venezuela', 'Code':	'+58'},
  {'Country':  'Yemen', 'Code':	'+998'},
  {'Country':  'Zambia', 'Code':	'+260'},
  {'Country':  'Zimbabwe', 'Code':	'+263'}
];

const styles = StyleSheet.create({
  container: {
    paddingTop: 5,
    flex: 1,
    //  alignItems: "center",
    // justifyContent: "flex-start",
    backgroundColor: 'white',
  },
  loginPane: {
    color: "white",
    // backgroundColor: 'powderblue',
    //ralignItems: 'flex-start',
    // justifyContent: 'flex-start',
    marginLeft: 5,
    paddingLeft: 15,
  },
  loginPaneTxt: {
    color: Constants.ShureFundTitleTextColor,
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
  },
  textInput: {
    borderStyle: "solid",
    borderWidth: 2,
    borderColor: "#cccccc",
    width: "90%",
    marginBottom: 15,
    fontSize: 20,
    fontStyle: "normal",
    backgroundColor: "white",
    padding: 5,
  },
  textLeft: {
    color: 'grey',
    //alignItems: "flex-end",
    // marginRight: 28,
    marginBottom: 1,
    paddingBottom: 1,
  },
  signInView: {
    flex: 1,
    marginTop: 15,
    marginBottom: 15,
    width: "100%",
    height: 40,
    // backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
  },
  signInBtn: {
    backgroundColor: Constants.LogoColour,
  },
  progressStyle: {
    flex:0.05,
    flexDirection: 'row',
    width: '90%',
    alignItems: 'center',
    //backgroundColor: 'red',
    marginLeft: 15,
    marginBottom: 10,
  },
});
export default function CountryCode({ navigation}) {
  return (
    <View style={styles.container}>
      <PageHeader2 />
      {/*  <ProgressBar progress={0.25}/>*/}
   {/*   <View style={styles.progressStyle}>
        <Progress.Bar progress={0.25} height={10} width={325} color={Constants.ScreenBackgroundColor}/>
      </View>*/}
      <View style={styles.loginPane}>
        <Text style={styles.loginPaneTxt}>Fill in your details</Text>
        <Text style={styles.textLeft} >Name</Text>
        <TextInput style={styles.textInput} placeholder={"User name"} />
        <Text style={styles.textLeft}>Email</Text>
        <TextInput style={styles.textInput} placeholder={"email"} />
        <View>
          <Text style={styles.textLeft}>Telephone</Text>
          {/* <SelectDropdown data={DialCodesArr.Code} onSelect={(selectedItem, index) => {
            console.log(selectedItem, index)
          }}
             />*/}
          <TextInput style={styles.textInput} placeholder={"Telephone number"} />

        </View>
      </View>
      {/*<Button>Sign In</Button>*/}
      <View style={styles.signInView}>
        <Button>Continue</Button>
      </View>
    </View>);
};

function SignInPressed(){
  alert("pressed");
}
//export default LoginScreen;
